import Head from 'next/head'
import AppLayout from '../components/AppLayout'
import MainMenuCard from '../components/Card'

export default function Home () {
  return (
    <div >
        <AppLayout>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <MainMenuCard link={'./learnToRead'} imgUrl='/background.jpg' />
          <MainMenuCard link={'./addMoreVelocity'} />
          <MainMenuCard link={'./chooseCorrectWord'} />
        </AppLayout>
    </div>
  )
}
